#!/usr/bin/env python3

"""
Write a coroutine called async_comprehension that returns a list of
random numbers between 0 and 10 generated by the async_generator coroutine.

Returns:
List[float]: A list of random numbers between 0 and 10.
"""
from typing import List
async_generator = __import__('0-async_generator').async_generator


async  def async_comprehension() -> List[float]:
    """
    returns a list of random numbers between 0 and 10.
    """
    return [val async for val in async_generator()]
